apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  labels:
    app: doctor-service
spec:
  selector:
    app: doctor-ms
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8082
#      nodePort: 31110